version: '3.6'

networks:
  localdev:
    name: localdev

services:
    persons-api:
        build: ./
        restart: always
        ports:
            - "7000:80"
        depends_on:
            - ms-sql-server
        networks:
            - localdev

    ms-sql-server:
        image:  mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        container_name: ms-sql-server
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=enes123456
            - MSSQL_PID=Express
        ports:
            - "1433:1433"
        networks:
            - localdev
    
    krakend_ce:
        image: devopsfaith/krakend:1.4.1
        volumes:
            - ./krakend:/etc/krakend
        ports:
            - "1234:1234"
            - "8080:8080"
            - "8090:8090"
        depends_on:
            - persons-api
        networks:
            - localdev